CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  passwordHash TEXT NOT NULL,
  name VARCHAR(255),
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  isVerified BOOLEAN NOT NULL DEFAULT FALSE,
  isBlocked BOOLEAN NOT NULL DEFAULT FALSE,
  failedLoginAttempts INT NOT NULL DEFAULT 0,
  lockedUntil TIMESTAMP NULL,
  lastSignedIn TIMESTAMP NULL,
  phoneNumber VARCHAR(50) NULL,
  profileImage TEXT NULL,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX users_email_unique ON users(email);

CREATE TABLE IF NOT EXISTS stores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sellerId INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  description TEXT NULL,
  logo TEXT NULL,
  banner TEXT NULL,
  isVerified BOOLEAN NOT NULL DEFAULT FALSE,
  isActive BOOLEAN NOT NULL DEFAULT TRUE,
  rating DOUBLE NULL,
  totalReviews INT NULL DEFAULT 0,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS otpVerifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phoneNumber VARCHAR(50) NOT NULL,
  countryCode VARCHAR(10) NULL,
  otp VARCHAR(10) NOT NULL,
  expiresAt TIMESTAMP NOT NULL,
  isUsed BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS passwordResets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  otp VARCHAR(10) NULL,
  isUsed BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  displayName VARCHAR(150) NOT NULL,
  description TEXT NULL,
  color VARCHAR(16) NULL,
  icon VARCHAR(64) NULL,
  priority INT NOT NULL DEFAULT 0,
  isSystem BOOLEAN NOT NULL DEFAULT FALSE,
  isActive BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  displayName VARCHAR(150) NOT NULL,
  description TEXT NULL,
  category VARCHAR(50) NOT NULL,
  action VARCHAR(50) NOT NULL,
  requiresApproval BOOLEAN NOT NULL DEFAULT FALSE,
  riskLevel VARCHAR(16) NULL,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rolePermissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  roleId INT NOT NULL,
  permissionId INT NOT NULL,
  granted BOOLEAN NOT NULL DEFAULT TRUE,
  grantedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS userRoles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  roleId INT NOT NULL,
  isPrimary BOOLEAN NOT NULL DEFAULT FALSE,
  expiresAt TIMESTAMP NULL,
  notes TEXT NULL,
  grantedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS userPermissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  permissionId INT NOT NULL,
  granted BOOLEAN NOT NULL DEFAULT TRUE,
  grantedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roleAuditLogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  action VARCHAR(100) NOT NULL,
  entityType VARCHAR(50) NOT NULL,
  entityId INT NULL,
  oldData TEXT NULL,
  newData TEXT NULL,
  changedBy INT NULL,
  ipAddress VARCHAR(50) NULL,
  userAgent TEXT NULL,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  type VARCHAR(100) NOT NULL,
  title VARCHAR(255) NULL,
  message TEXT NULL,
  isRead BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notificationQueue (
  id INT AUTO_INCREMENT PRIMARY KEY,
  notificationId INT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notificationSettings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  category VARCHAR(50) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notificationLogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  notificationId INT NULL,
  status VARCHAR(50) NOT NULL,
  error TEXT NULL,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supportedCurrencies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(10) NOT NULL,
  name VARCHAR(100) NULL,
  symbol VARCHAR(10) NULL,
  isActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS currencyConversions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fromCode VARCHAR(10) NOT NULL,
  toCode VARCHAR(10) NOT NULL,
  rate DOUBLE NOT NULL,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sellerWallet (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sellerId INT NOT NULL,
  balance DOUBLE NOT NULL DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX sellerWallet_sellerId_unique ON sellerWallet(sellerId);

CREATE TABLE IF NOT EXISTS commissionLogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sellerId INT NULL,
  amount DOUBLE NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sellerWithdrawals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sellerId INT NOT NULL,
  amount DOUBLE NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS platformCommissionRevenue (
  id INT AUTO_INCREMENT PRIMARY KEY,
  amount DOUBLE NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  token TEXT NULL,
  expiresAt TIMESTAMP NULL,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
